apiVersion: 1

contactPoints:
  - orgId: 1
    name: fandrops-email
    receivers:
      - uid: fandrops-email-receiver
        type: email
        settings:
          addresses: xxjyj1022@gmail.com
          singleEmail: false
        disableResolveMessage: false
